"""initial schema

Revision ID: f58835187f86
Revises: 
Create Date: 2026-09-26 17:34:48.853232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58835187f86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='devicestatus'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('first_discovered', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_percent', sa.Float(), nullable=True),
    sa.Column('is_snmp_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=True)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('alert_type', sa.Enum('PORT_SCAN_SUSPECTED', 'EXCESSIVE_CONNECTIONS', 'ICMP_ANOMALY', 'SUSPICIOUS_SERVICE', 'BANDWIDTH_ANOMALY', 'DEVICE_UNREACHABLE', 'HIGH_LATENCY', 'HIGH_PACKET_LOSS', 'ML_ANOMALY', name='alerttype'), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('evidence', sa.String(length=2000), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_alert_type'), 'security_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_security_alerts_id'), 'security_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_security_alerts_severity'), 'security_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_security_alerts_source_ip'), 'security_alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_security_alerts_timestamp'), 'security_alerts', ['timestamp'], unique=False)
    op.create_table('traffic_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('packets_per_second', sa.Float(), nullable=False),
    sa.Column('bytes_per_second', sa.Float(), nullable=False),
    sa.Column('tcp_count', sa.Integer(), nullable=False),
    sa.Column('udp_count', sa.Integer(), nullable=False),
    sa.Column('icmp_count', sa.Integer(), nullable=False),
    sa.Column('other_count', sa.Integer(), nullable=False),
    sa.Column('unique_src_ips', sa.Integer(), nullable=False),
    sa.Column('unique_dst_ips', sa.Integer(), nullable=False),
    sa.Column('unique_dst_ports', sa.Integer(), nullable=False),
    sa.Column('avg_packet_size', sa.Float(), nullable=False),
    sa.Column('top_src_ips_json', sa.String(length=1000), nullable=True),
    sa.Column('top_dst_ips_json', sa.String(length=1000), nullable=True),
    sa.Column('top_dst_ports_json', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_records_id'), 'traffic_records', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_records_window_start'), 'traffic_records', ['window_start'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('oper_status', sa.String(length=20), nullable=True),
    sa.Column('admin_status', sa.String(length=20), nullable=True),
    sa.Column('in_octets', sa.Integer(), nullable=True),
    sa.Column('out_octets', sa.Integer(), nullable=True),
    sa.Column('in_errors', sa.Integer(), nullable=True),
    sa.Column('out_errors', sa.Integer(), nullable=True),
    sa.Column('last_polled', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_reachable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metrics_device_id'), 'monitoring_metrics', ['device_id'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_id'), 'monitoring_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_timestamp'), 'monitoring_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_metrics_timestamp'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_id'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_device_id'), table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_index(op.f('ix_interfaces_id'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_traffic_records_window_start'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_id'), table_name='traffic_records')
    op.drop_table('traffic_records')
    op.drop_index(op.f('ix_security_alerts_timestamp'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_source_ip'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_severity'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_alert_type'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
